# Generated by Django 3.2 on 2021-04-16 04:55

import contents.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainFiles',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('trainfile', models.FileField(blank=True, upload_to=contents.models.filepath)),
                ('client', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
