# Generated by Django 3.2 on 2021-04-16 05:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0002_trainfiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainfiles',
            name='upload_date',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
    ]
