# Generated by Django 3.2 on 2021-04-16 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0004_alter_trainfiles_upload_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='intents',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='intents', to='contents.intents'),
        ),
        migrations.AlterField(
            model_name='intents',
            name='domain',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='domain_name', to='contents.domains'),
        ),
    ]
