# Generated by Django 3.2 on 2021-04-16 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0005_auto_20210416_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversations',
            name='remarks',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
