# Generated by Django 3.2 on 2021-04-19 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0008_trainfiles_domain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='msg',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='message',
            name='response',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
