# Generated by Django 3.2 on 2021-04-20 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0010_auto_20210419_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='entity',
            field=models.CharField(default=None, max_length=1000),
        ),
        migrations.AlterField(
            model_name='entity',
            name='entity_type',
            field=models.CharField(default=None, max_length=1000),
        ),
        migrations.AlterField(
            model_name='entity',
            name='synonyms',
            field=models.CharField(default=None, max_length=1000),
        ),
        migrations.AlterField(
            model_name='entity',
            name='value',
            field=models.CharField(default=None, max_length=1000),
        ),
        migrations.AlterField(
            model_name='intents',
            name='intent',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AlterField(
            model_name='intents',
            name='response',
            field=models.CharField(default=None, max_length=5000),
        ),
        migrations.AlterField(
            model_name='intents',
            name='user_say',
            field=models.CharField(default=None, max_length=5000),
        ),
    ]
