# Generated by Django 3.2 on 2021-04-20 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0012_alter_trainfiles_trainfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainfiles',
            name='domain',
            field=models.CharField(max_length=100),
        ),
    ]
