# Generated by Django 3.2 on 2021-04-28 09:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0013_alter_trainfiles_domain'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversations',
            name='mobile_no',
        ),
        migrations.RemoveField(
            model_name='conversations',
            name='user_name',
        ),
        migrations.AlterField(
            model_name='conversations',
            name='user_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
