# Generated by Django 3.2 on 2021-04-29 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0014_auto_20210428_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='response',
            field=models.TextField(blank=True),
        ),
    ]
